[platformio]
extra_configs = secrets.ini

[env:EcoSmart]
platform = espressif32
board = esp32-wrover-e-n16r8
board_build.partitions = default_16MB.csv
board_build.filesystem = littlefs
framework = arduino
monitor_filters = esp32_exception_decoder
monitor_speed = 115200
build_type = debug

build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -mfix-esp32-psram-cache-strategy=memw
    -DCORE_DEBUG_LEVEL=3
    -DUSE_LittleFS
    -DWIFI_SSID=\"${secrets.wifi_ssid}\"
    -DWIFI_PASSWORD=\"${secrets.wifi_password}\"
    -DAPI_BASE_URL=\"${secrets.api_base_url}\"
    -DOWNER_USERNAME=\"${secrets.owner_username}\"
    -DOWNER_PASSWORD=\"${secrets.owner_password}\"

board_build.psram = enable
lib_deps =
    tas5805m
    ESP32Async/ESPAsyncWebServer
    ESP32Async/AsyncTCP
    ipdotsetaf/ESPAsyncHTTPUpdateServer @ ^3.0.0
    bblanchon/ArduinoJson @ ^7.4.2
    exocet22/btAudio @ ^1.1.0
    fastled/FastLED
    adafruit/DHT sensor library @ ^1.4.7
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    ahmedarif193/HLW8032 @ ^1.2